In [22]:
import datetime
import random
import pandas 
import numpy
# 데이터 경로
PATH = "C:/Users/WAI/OneDrive/03.WORKSPACE/00.DATA/99.KAGGLE/insurance/"

# 데이터 명
DATA_NAME = "14. Learning from Imbalaced Insurance Data/aug_train.csv"

df = pandas.read_csv(PATH + DATA_NAME)

date = pandas.date_range('1970-01-01', '2010-01-01', freq='d')
date2 = pandas.date_range('1990-01-01', '2010-01-01', freq='d')
l_date = []
l_date2 = []
for i, j  in zip(date, date2):
    l_date.append(str(j).split(" ")[0])
    l_date2.append(str(j).split(" ")[0])
    
exit_flag = True
while exit_flag:
    l_date.extend(l_date)
    l_date2.extend(l_date2)
    if len(l_date) >= len(df):
        exit_flag = False


random.shuffle(l_date)
random.shuffle(l_date2)
df['birth_date'] = l_date[:len(df)]
df['insure_date'] = l_date2[:len(df)]
df.insure_date = df.insure_date.str.replace("-","")
df["birth_date"] = pandas.to_datetime(df['birth_date'], format="%Y-%m-%d")


# Null 값 생성

ratio = 0.003
#print(random.sample(range(0,len(df)), int(len(df)*0.05)))

rd_index = random.sample(range(0,len(df)), int(len(df)*ratio))
print(len(rd_index))

print(df.columns.values)
'''
['id' 'Gender' 'Age' 'Driving_License' 'Region_Code' 'Previously_Insured'
 'Vehicle_Age' 'Vehicle_Damage' 'Annual_Premium' 'Policy_Sales_Channel'
 'Vintage' 'Response' 'birth_date' 'insure_date']
'''

print(df.head())
# df["Vintage"][rd_index] = numpy.nan
# df["Annual_Premium"][rd_index] = numpy.nan
# df["Age"][rd_index] = numpy.nan
# df["Driving_License"][rd_index] = numpy.nan

df.isnull().sum()
rd_index = random.sample(range(0,len(df)),7)
#df["Policy_Sales_Channel"][rd_index]= 2999
#df["Vintage"][rd_index] = 4778


#df.to_csv(PATH + "14. Learning from Imbalaced Insurance Data/aug_train_mod.csv")



#print(random.shuffle(list(map(lambda x : str(x).split(' ')[0] ,  pandas.date_range(start='2020-01-01',end='2021-01-01').tolist()))))

1146
['id' 'Gender' 'Age' 'Driving_License' 'Region_Code' 'Previously_Insured'
 'Vehicle_Age' 'Vehicle_Damage' 'Annual_Premium' 'Policy_Sales_Channel'
 'Vintage' 'Response' 'birth_date' 'insure_date']
       id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  167647    Male   22                1          7.0                   1
1   17163    Male   42                1         28.0                   0
2   32023  Female   66                1         33.0                   0
3   87447  Female   22                1         33.0                   0
4  501933    Male   28                1         46.0                   1

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    < 1 Year             No          2630.0                 152.0       16
1    1-2 Year            Yes         43327.0                  26.0      135
2    1-2 Year            Yes         35841.0                 124.0      253
3    < 1 Year             No         27645.0                 152.0       69
4    < 1 Year             No         29023.0                 152.0      211

   Response birth_date insure_date
0         0 1993-03-12    19911206
1         0 1990-11-13    20090201
2         0 1995-02-16    19910820
3         0 2000-03-26    20060304
4         0 2008-11-15    19910408

id                      0
Gender                  0
Age                     0
Driving_License         0
Region_Code             0
Previously_Insured      0
Vehicle_Age             0
Vehicle_Damage          0
Annual_Premium          0
Policy_Sales_Channel    0
Vintage                 0
Response                0
birth_date              0
insure_date             0
dtype: int64

In [26]:
df = pandas.read_csv(PATH + "14. Learning from Imbalaced Insurance Data/aug_train_mod.csv", index_col = False)

In [34]:
#df.set_index("id", inplace=True)
df.head()
df.isnull().sum()
df.describe()

,id,Age,Driving_License,Region_Code,Previously_Insured,Annual_Premium,Policy_Sales_Channel,Vintage,Response,insure_date
count,382154.000000,370690.000000,381008.000000,382154.000000,382154.000000,380244.000000,382154.000000,363047.000000,382154.000000,3.821540e+05
mean,234392.953477,38.543807,0.998113,26.406867,0.489182,30711.645604,111.992676,154.138302,0.163811,1.999579e+07
std,139527.487326,15.225590,0.043400,13.181241,0.499884,17060.579359,55.674428,83.724377,0.370104,5.765952e+04
min,1.000000,20.000000,0.000000,0.000000,0.000000,2630.000000,1.000000,10.000000,0.000000,1.990010e+07
25%,115006.250000,25.000000,1.000000,15.000000,0.000000,24547.000000,26.000000,81.000000,0.000000,1.995011e+07
50%,230461.500000,36.000000,1.000000,28.000000,0.000000,31692.000000,145.000000,154.000000,0.000000,2.000011e+07
75%,345434.750000,49.000000,1.000000,35.000000,1.000000,39448.250000,152.000000,227.000000,0.000000,2.005010e+07
max,508145.000000,85.000000,1.000000,52.000000,1.000000,540165.000000,2999.000000,299.000000,1.000000,2.010010e+07

In [35]:
# 이상치 추가
df.reset_index(inplace=True)
rd_index = random.sample(range(0,len(df)),7)
#df["Policy_Sales_Channel"][rd_index]= 2999
#df["Vintage"][rd_index] = 4778

C:\Users\WAI\Anaconda3\envs\analysis\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.