In [5]:
import datetime
import random
import pandas 
import numpy
import warnings
warnings.filterwarnings(action="ignore")
# 데이터 경로
PATH = "C:/Users/WAI/OneDrive/03.WORKSPACE/00.DATA/99.KAGGLE/insurance/"

# 데이터 명
DATA_NAME = "14. Learning from Imbalaced Insurance Data/aug_train.csv"

df = pandas.read_csv(PATH + DATA_NAME)

date = pandas.date_range('1970-01-01', '2010-01-01', freq='d')
date2 = pandas.date_range('1990-01-01', '2010-01-01', freq='d')
l_date = []
l_date2 = []
for i, j  in zip(date, date2):
    l_date.append(str(j).split(" ")[0])
    l_date2.append(str(j).split(" ")[0])
    
exit_flag = True
while exit_flag:
    l_date.extend(l_date)
    l_date2.extend(l_date2)
    if len(l_date) >= len(df):
        exit_flag = False


random.shuffle(l_date)
random.shuffle(l_date2)
df['birth_date'] = l_date[:len(df)]
df['insure_date'] = l_date2[:len(df)]
df.insure_date = df.insure_date.str.replace("-","")
df["birth_date"] = pandas.to_datetime(df['birth_date'], format="%Y-%m-%d")


# Null 값 생성

ratio = 0.003
rd_index = random.sample(range(0,len(df)), int(len(df)*ratio))
'''
['id' 'Gender' 'Age' 'Driving_License' 'Region_Code' 'Previously_Insured'
 'Vehicle_Age' 'Vehicle_Damage' 'Annual_Premium' 'Policy_Sales_Channel'
 'Vintage' 'Response' 'birth_date' 'insure_date']
'''

print(df.head())
ratio = 0.003
rd_index = random.sample(range(0,len(df)), int(len(df)*ratio))
df["Vintage"][rd_index] = numpy.nan
ratio = 0.001
rd_index = random.sample(range(0,len(df)), int(len(df)*ratio))
df["Annual_Premium"][rd_index] = numpy.nan
ratio = 0.07
rd_index = random.sample(range(0,len(df)), int(len(df)*ratio))
df["Age"][rd_index] = numpy.nan
ratio = 0.005
rd_index = random.sample(range(0,len(df)), int(len(df)*ratio))
df["Driving_License"][rd_index] = numpy.nan

df.isnull().sum()
ratio = 0.0005
rd_index = random.sample(range(0,len(df)), int(len(df)*ratio))
df["Policy_Sales_Channel"][rd_index]= 2999
ratio = 0.00001
rd_index = random.sample(range(0,len(df)), int(len(df)*ratio))
df["Vintage"][rd_index] = 4778


df.to_csv(PATH + "14. Learning from Imbalaced Insurance Data/aug_train_mod.csv", index=False)



#print(random.shuffle(list(map(lambda x : str(x).split(' ')[0] ,  pandas.date_range(start='2020-01-01',end='2021-01-01').tolist()))))

       id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  167647    Male   22                1          7.0                   1
1   17163    Male   42                1         28.0                   0
2   32023  Female   66                1         33.0                   0
3   87447  Female   22                1         33.0                   0
4  501933    Male   28                1         46.0                   1

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    < 1 Year             No          2630.0                 152.0       16
1    1-2 Year            Yes         43327.0                  26.0      135
2    1-2 Year            Yes         35841.0                 124.0      253
3    < 1 Year             No         27645.0                 152.0       69
4    < 1 Year             No         29023.0                 152.0      211

   Response birth_date insure_date
0         0 1997-08-09    20000106
1         0 2008-04-11    19960816
2         0 2004-08-18    20010704
3         0 1999-11-18    19900910
4         0 1992-09-02    19971026

In [3]:
df = pandas.read_csv(PATH + "14. Learning from Imbalaced Insurance Data/aug_train_mod.csv", index_col = False)

In [4]:
#df.set_index("id", inplace=True)
df.head()
df.isnull().sum()
df.describe()

,Unnamed: 0,id,Age,Driving_License,Region_Code,Previously_Insured,Annual_Premium,Policy_Sales_Channel,Vintage,Response,insure_date
count,382154.000000,382154.000000,355404.000000,380244.000000,382154.000000,382154.000000,381772.000000,382154.000000,381008.000000,382154.000000,3.821540e+05
mean,191076.500000,234392.953477,38.541648,0.998109,26.406867,0.489182,30712.032553,113.381187,154.234961,0.163811,1.999568e+07
std,110318.501723,139527.487326,15.222766,0.043443,13.181241,0.499884,17062.184193,84.316952,84.734476,0.370104,5.766598e+04
min,0.000000,1.000000,20.000000,0.000000,0.000000,0.000000,2630.000000,1.000000,10.000000,0.000000,1.990010e+07
25%,95538.250000,115006.250000,25.000000,1.000000,15.000000,0.000000,24546.000000,26.000000,82.000000,0.000000,1.995010e+07
50%,191076.500000,230461.500000,36.000000,1.000000,28.000000,0.000000,31693.000000,145.000000,154.000000,0.000000,2.000010e+07
75%,286614.750000,345434.750000,49.000000,1.000000,35.000000,1.000000,39447.000000,152.000000,227.000000,0.000000,2.005010e+07
max,382153.000000,508145.000000,85.000000,1.000000,52.000000,1.000000,540165.000000,2999.000000,4778.000000,1.000000,2.010010e+07

In [35]:
# 이상치 추가
df.reset_index(inplace=True)
rd_index = random.sample(range(0,len(df)),7)
#df["Policy_Sales_Channel"][rd_index]= 2999
#df["Vintage"][rd_index] = 4778

C:\Users\WAI\Anaconda3\envs\analysis\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.